name: 'Rebol-RDAP CI'
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Rebol for the test
      uses: oldes/install-rebol@v3.18.0

    - name: Test RDAP API module
      run:  ./rebol3 ci-test.r3

